# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketid', models.AutoField(primary_key=True, serialize=False, verbose_name='TicketID')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('sector', models.CharField(max_length=30, verbose_name='Bereich')),
                ('category', models.CharField(max_length=30, verbose_name='Art')),
                ('subject', models.CharField(max_length=50, verbose_name='Betreff')),
                ('description', models.CharField(max_length=400, verbose_name='Beschreibung')),
                ('creationdatetime', models.DateTimeField(verbose_name='Erstellungsdatum')),
                ('creator', models.CharField(max_length=40, verbose_name='Ersteller')),
                ('responsible_person', models.CharField(blank=True, max_length=40, verbose_name='Verantwortlicher')),
                ('comment', models.CharField(max_length=100, verbose_name='Kommentar')),
                ('solution', models.CharField(max_length=400, verbose_name='Lösung')),
                ('keywords', models.CharField(max_length=100, verbose_name='Keywords')),
                ('closingdatetime', models.DateTimeField(blank=True, null=True, verbose_name='Abschlussdatum')),
                ('workinghours', models.FloatField(default=0.0, verbose_name='Bearbeitungszeit')),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
