# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('sector', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('creationdate', models.DateField()),
                ('ticketid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('closingdate', models.DateField()),
                ('comment', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=400)),
                ('keywords', models.CharField(max_length=100)),
                ('responsible_person', models.CharField(max_length=40)),
                ('creator', models.CharField(max_length=40)),
            ],
        ),
    ]
