# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(default='moderate', max_length=20, verbose_name='Priorität'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creationdatetime',
            field=models.DateTimeField(verbose_name='Erstell-Zeitpunkt'),
        ),
    ]
