# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20170829_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='responsible_person',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Verantwortliche/r'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sector',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Bereich'),
        ),
    ]
