# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20170905_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='responsible_person',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Verantwortliche/r'),
        ),
    ]
