# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20170804_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
