# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20170810_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='workinghours',
            field=models.FloatField(default=0.0, verbose_name='Bearbeitungszeit'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(max_length=30, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='closingdatetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Abschlussdatum'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.CharField(max_length=100, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creationdatetime',
            field=models.DateTimeField(verbose_name='Erstellungsdatum'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creator',
            field=models.CharField(max_length=40, verbose_name='Ersteller'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='keywords',
            field=models.CharField(max_length=100, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=40, verbose_name='Verantwortlicher'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sector',
            field=models.CharField(max_length=30, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solution',
            field=models.CharField(max_length=400, verbose_name='Lösung'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Betreff'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='TicketID'),
        ),
    ]
