# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20171004_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvingmeasures',
            name='ticketid',
        ),
        migrations.AddField(
            model_name='solvingmeasures',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
    ]
