# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20171013_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measures',
            old_name='isSolution',
            new_name='is_solution',
        ),
    ]
